version: '3.8'

services:
  leaderboard-postgres:
    image: postgres:13
    container_name: leaderboard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaderboard-app
    ports:
      - "3000:3000"
    depends_on:
      - leaderboard-postgres

volumes:
  postgres-data:
