---
- name: Configure PostgreSQL Server
  hosts: db
  become: true
  remote_user: azureuser

  vars:
    postgresql_data_directory: /var/lib/postgresql/{{ postgresql_version }}/main
    postgresql_conf_directory: /etc/postgresql/{{ postgresql_version }}/main
    postgresql_listen_addresses: '*'
    postgresql_max_connections: 100
    postgresql_port: 5432
    postgresql_shared_buffers: '128MB'
    postgresql_database: mydatabase
    postgresql_user: myuser
    postgresql_password: mypassword
    replication_user: replica_user
    replication_password: replica_password
    postgresql_hba_entries:
      - { type: 'local', database: 'all', user: 'all', address: '', method: 'trust' }
      - { type: 'host', database: 'all', user: 'all', address: '127.0.0.1/32', method: 'md5' }
      - { type: 'host', database: 'all', user: 'all', address: '::1/128', method: 'md5' }
      - { type: 'host', database: 'all', user: 'all', address: '0.0.0.0/0', method: 'md5' }
      
  tasks:
    - name: Add pgdg repo to sources.list.d
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pgdg.list
        line: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        create: true

    - name: Download PostgreSQL key and add it to system keyring
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
    
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PostgreSQL and PostgreSQL Client
      ansible.builtin.apt:
        name: 
          - postgresql
          - postgresql-client
        state: present

    - name: Consult PostgreSQL Version
      ansible.builtin.shell: |
        ls /etc/postgresql/ | cat
      register: postgres_version_output

    - name: Set version number as fact
      set_fact:
        postgresql_version: "{{ postgres_version_output.stdout }}"

    - name: Install python, psycopg2 and acl
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-psycopg2
        - acl

    - name: Ensure PostgreSQL is started and enabled
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Ensure PostgreSQL data directory exists
      ansible.builtin.file:
        path: "{{ postgresql_data_directory }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Initialize PostgreSQL data directory
      become_user: postgres
      ansible.builtin.command: "/usr/lib/postgresql/{{ postgresql_version }}/bin/initdb -D {{ postgresql_data_directory }}"
      args:
        creates: "{{ postgresql_data_directory }}/PG_VERSION"
      when: primary is defined and primary

    - name: Deploy postgresql.conf from template
      ansible.builtin.template:
        src: ../templates/postgresql.conf.j2
        dest: "{{ postgresql_conf_directory }}/postgresql.conf"
        owner: postgres
        group: postgres
        mode: '0644'
      notify: Restart PostgreSQL

    - name: Deploy pg_hba.conf from template
      ansible.builtin.template:
        src: ../templates/pg_hba.conf.j2
        dest: "{{ postgresql_conf_directory }}/pg_hba.conf"
        owner: postgres
        group: postgres
        mode: '0640'
      notify: Reload PostgreSQL

    - name: Allow replication connections in pg_hba.conf
      lineinfile:
        path: "{{ postgresql_conf_directory }}/pg_hba.conf"
        line: "host replication {{ replication_user }} {{ groups['db'][1] }}/32 md5"
        create: yes
      register: pg_hba_changed
      changed_when: true  # Esto asegura que la tarea se marque como cambiada incluso si no produce cambios en el sistema
      when: primary is defined and primary

    - name: Restart PostgreSQL service on the primary server
      ansible.builtin.service:
        name: postgresql
        state: restarted
      when: primary is defined and primary and pg_hba_changed is succeeded

    - name: Ensure PostgreSQL data directory has correct permissions
      ansible.builtin.file:
        path: "{{ postgresql_data_directory }}"
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Create PostgreSQL database - mydatabase
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ postgresql_database }}"
      when: primary is defined and primary

    - name: Create PostgreSQL user - myuser
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ postgresql_user }}"
        password: "{{ postgresql_password }}"
      when: primary is defined and primary

    - name: Allow user myuser to do all actions in database mydatabase
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: "{{ postgresql_database }}"
        state: present
        privs: ALL
        objs: ALL_IN_SCHEMA
        role: "{{ postgresql_user }}"
      when: primary is defined and primary

    - name: Allow incoming connections on port 5432
      community.general.ufw:
        rule: allow
        port: 5432
        proto: tcp

    - name: Allow incoming connections on port 22
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Create replication user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ replication_user }}"
        password: "{{ replication_password }}"
        role_attr_flags: "REPLICATION"
      when: primary is defined and primary

    - name: Allow replication user replication privileges
      become: true
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: "{{ postgresql_database }}"
        state: present
        privs: ALL
        objs: ALL_IN_SCHEMA
        role: "{{ replication_user }}"
      when: primary is defined and primary

    - name: Add replication configuration to postgresql.conf
      lineinfile:
        path: "{{ postgresql_conf_directory }}/postgresql.conf"
        regexp: "^#?wal_level = "
        line: "wal_level = logical"
      notify: Restart PostgreSQL
      when: primary is defined and primary

    - name: Add replication configuration to postgresql.conf
      lineinfile:
        path: "{{ postgresql_conf_directory }}/postgresql.conf"
        regexp: "^#?max_wal_senders = "
        line: "max_wal_senders = 3"
      notify: Restart PostgreSQL
      when: primary is defined and primary

    - name: Add replication configuration to postgresql.conf
      lineinfile:
        path: "{{ postgresql_conf_directory }}/postgresql.conf"
        regexp: "^#?wal_log_hints = "
        line: "wal_log_hints = on"
      notify: Restart PostgreSQL
      when: primary is defined and primary

    - name: Ensure PostgreSQL is stopped on replica
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
      when: secondary is defined and secondary

    - name: Clean PostgreSQL data directory on replica
      ansible.builtin.file:
        path: "{{ postgresql_data_directory }}"
        state: absent
      when: secondary is defined and secondary

    - name: Perform base backup from primary to replica
      become: true
      become_user: postgres
      ansible.builtin.command: |
        pg_basebackup -h {{ groups['db'][0] }} -U {{ replication_user }} -X stream -C -S replica_lpm -v -R -D {{ postgresql_data_directory }}
      environment:
        PGPASSWORD: "{{ replication_password }}"
      when: secondary is defined and secondary

    - name: Create PostgreSQL data directory on replica
      ansible.builtin.file:
        path: "{{ postgresql_data_directory }}"
        recurse: yes
        owner: postgres
        group: postgres
        mode: '0700'
      when: secondary is defined and secondary

    - name: Ensure PostgreSQL is started on replica
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true
      when: secondary is defined and secondary

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.systemd:
        name: postgresql
        state: restarted

    - name: Reload PostgreSQL
      ansible.builtin.systemd:
        name: postgresql
        state: reloaded
