- name: Install Semaphore UI
  hosts: semaphore
  become: true
  remote_user: azureuser

  vars:
    semaphore_admin_user: admin
    semaphore_admin_email: azul-k@hotmail.com
    semaphore_admin_password: admin

  tasks:
  - name: Install semaphore with Snap
    community.general.snap:
      name: semaphore
      state: present

  - name: Create admin user 
    command: semaphore user add --admin --login {{ semaphore_admin_user }} --name={{ semaphore_admin_user }} --email={{ semaphore_admin_email }} --password={{ semaphore_admin_password }}

  - name: Check status of Semaphore service with Snap
    community.general.snap:
      name: semaphore

  