---
- name: Configure Webserver
  hosts: ws
  become: true
  remote_user: azureuser
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required system packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm

    - name: Copy web server code into vm
      ansible.builtin.copy:
        src: ../web-server
        dest: ./
      notify: Restart node-app

    - name: npm install
      ansible.builtin.command:
      become: true
      args:
        chdir: web-server/
        cmd: npm install

    - name: Copy systemd service file for Node.js app
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=My Node.js App
          After=network.target

          [Service]
          ExecStart=/usr/bin/npm start
          WorkingDirectory=/home/azureuser/web-server/
          Restart=always
          User=root
          Group=root
          EnvironmentFile=/home/azureuser/web-server/.env
          Environment=PATH=/usr/bin:/usr/local/bin
          Environment=NODE_ENV=production

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node-app.service
        mode: '0644'
      notify: Restart node-app

    - name: Reload systemd to pick up new service file
      ansible.builtin.command: systemctl daemon-reload

    - name: Enable and start Node.js app service
      ansible.builtin.systemd:
        name: node-app
        enabled: yes
        state: started

    - name: Restart Nginx in localhost
      ansible.builtin.systemd:
          name: nginx
          state: restarted
      delegate_to: localhost

  handlers:
    - name: Restart node-app
      ansible.builtin.systemd:
        name: node-app
        state: restarted